#!/usr/bin/env node
/**
 * One-command setup for the Miracle Exterminating Service Management System.
 *
 * This runs automatically before `npm run dev` and `npm run build` (via the
 * predev / prebuild hooks) so nobody has to configure the database by hand.
 *
 * It will:
 *   1. Create a .env file (with a generated AUTH_SECRET) if one is missing.
 *   2. Start the PostgreSQL Docker container (docker compose up -d).
 *   3. Wait until the database is ready to accept connections.
 *   4. Generate the Prisma client and push the schema.
 *   5. Seed roles and the default admin / manager accounts.
 *
 * Skip it entirely with:  SKIP_DB_SETUP=1 npm run build
 */

import { execSync, spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const rootDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(rootDir, ".env");

// Connection string for the bundled Docker database (host port 5433).
const DOCKER_DATABASE_URL =
  "postgresql://mis:mis_password@localhost:5433/mis5305?schema=public";

function log(message) {
  console.log(`\x1b[36m[setup]\x1b[0m ${message}`);
}

function fail(message) {
  console.error(`\x1b[31m[setup] ${message}\x1b[0m`);
  process.exit(1);
}

function run(command, extraEnv) {
  execSync(command, {
    cwd: rootDir,
    stdio: "inherit",
    env: extraEnv ? { ...process.env, ...extraEnv } : process.env,
  });
}

function canRun(command, args) {
  const result = spawnSync(command, args, { stdio: "ignore" });
  return result.status === 0;
}

// Cross-platform blocking sleep (no shell, works on Windows/macOS/Linux).
function sleep(ms) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

// 1. Ensure a .env file exists.
function ensureEnv() {
  if (existsSync(envPath)) {
    log(".env already present.");
    return readFileSync(envPath, "utf8");
  }
  log("Creating .env with a generated AUTH_SECRET...");
  const secret = randomBytes(32).toString("base64");
  const contents =
    `# Generated by scripts/setup.mjs\n` +
    `DATABASE_URL="${DOCKER_DATABASE_URL}"\n` +
    `AUTH_SECRET="${secret}"\n`;
  writeFileSync(envPath, contents);
  return contents;
}

function readDatabaseUrl(envContents) {
  const match = envContents.match(/^DATABASE_URL\s*=\s*"?([^"\n]+)"?/m);
  return match ? match[1].trim() : "";
}

function isLocalDatabase(url) {
  return /@(localhost|127\.0\.0\.1)/.test(url);
}

// 2 + 3. Start Docker and wait for the database.
function startDatabase() {
  const hasDocker = canRun("docker", ["--version"]);
  if (!hasDocker) {
    fail(
      "Docker is not installed or not on PATH. Install Docker Desktop and try again " +
        "(https://www.docker.com/products/docker-desktop/)."
    );
  }
  if (!canRun("docker", ["info"])) {
    fail("Docker is installed but not running. Start Docker Desktop and try again.");
  }

  log("Starting PostgreSQL container (docker compose up -d)...");
  run("docker compose up -d");

  log("Waiting for the database to become ready...");
  const deadline = Date.now() + 60_000;
  while (Date.now() < deadline) {
    const ready = spawnSync(
      "docker",
      ["compose", "exec", "-T", "db", "pg_isready", "-U", "mis", "-d", "mis5305"],
      { cwd: rootDir, stdio: "ignore" }
    );
    if (ready.status === 0) {
      log("Database is ready.");
      return;
    }
    sleep(2000);
  }
  fail("Timed out waiting for the database to become ready.");
}

// 4 + 5. Prisma client, schema, and seed data.
function migrateAndSeed(databaseUrl) {
  // Force the .env value so a shell-exported DATABASE_URL can't silently
  // point Prisma at a different database.
  const env = { DATABASE_URL: databaseUrl };

  log("Generating Prisma client...");
  run("npx prisma generate", env);

  log("Applying database schema (prisma db push)...");
  run("npx prisma db push", env);

  log("Seeding roles and default accounts...");
  run("npx prisma db seed", env);
}

function main() {
  if (process.env.SKIP_DB_SETUP === "1") {
    log("SKIP_DB_SETUP=1 set — skipping database setup.");
    return;
  }

  const envContents = ensureEnv();
  const databaseUrl = readDatabaseUrl(envContents);

  if (isLocalDatabase(databaseUrl)) {
    startDatabase();
  } else {
    log("DATABASE_URL points to an external host — skipping Docker startup.");
  }

  migrateAndSeed(databaseUrl);

  console.log(
    "\n\x1b[32m[setup] Done!\x1b[0m Start the app with \x1b[1mnpm run dev\x1b[0m.\n" +
      "  Admin login:   admin / admin123\n" +
      "  Manager login: manager / manager123\n"
  );
}

main();
